name: CGS-Core
main: org.core.cgs.Core
version: 2.1
api-version: 1.13
author: Fictitious_Rotor
depend: [ LightAPI, Holograms ]

commands:
  # Infinite chests
  infinitechests:
    description: InfiniteChests parent command
    usage: Did not recognise the provided sub command. Run '/infinitechests help' for available subcommands!

  # Light Utils
  lightutils:
    description: LightUtils parent command
    usage: Did not recognise provided sub command. Run '/infinitechests help' for available subcommands!