const args = process.argv
const fileTemplate = args[2];
const codeToInsert = args[3];

const filePieces = fileTemplate.split("        // Autogenerated Content");

console.log(filePieces[0]);
console.log(codeToInsert);
console.log(filePieces[1]);